### PR TITLE
Testflight mode

### PR DESCRIPTION
**Pull request by joenoon**
This allows for configuration changes when building for testflight and also cleans up files between testflight/non-testflight device builds.

Not sure about the gemspec changes.  I needed a gemspec locally for bundler, and found it odd not to have one, so I just switched the Rakefile style to a gemspec.

### CODE REVIEW

**Comment by lrz** [comment]
@Watson1978 can you check/merge this? it is related to ticket #109. Thanks :-)

**Comment by Watson1978** [comment]
@lrz OK, i see.

**Comment by Watson1978** [comment]
Looks good.

I have one request. I think better that testflight method yield testflight object when given a block. like:

``` ruby
diff --git a/lib/motion/project/testflight.rb b/lib/motion/project/testflight.rb
index a14847b..a01eaeb 100644
--- a/lib/motion/project/testflight.rb
+++ b/lib/motion/project/testflight.rb
@@ -82,7 +82,7 @@ module Motion; module Project; class Config

   def testflight
     @testflight ||= TestFlightConfig.new(self)
-    yield if block_given? && testflight?
+    yield @testflight if block_given? && testflight?
     @testflight
   end

```

Then, we could configure 

``` ruby
app.testflight do
  app.testflight.sdk = 'vendor/TestFlight'
  app.testflight.api_token = '<insert your API token here>'
  app.testflight.team_token = '<insert your team token here>'
  app.testflight.notify = true # default is false
end
```

and also could use block parameter:

``` ruby
app.testflight do |flight|
  flight.sdk = 'vendor/TestFlight'
  flight.api_token = '<insert your API token here>'
  flight.team_token = '<insert your team token here>'
  flight.notify = true # default is false
end
```

What do you think?

**Comment by lrz** [comment]
I think it's a good idea :)

**Comment by Watson1978** [comment]
OK thanks.

I will commit my request after merging pull request :)

@joenoon Thank you for spending your time for this pull request!!

**Pull request merged**
