### PR TITLE
Update to use Release rather than Development build for TestFlight

### PR DESCRIPTION
**Pull request by chrisradford**
As per ticket #19 — in keeping with the TestFlight guidelines.

### CODE REVIEW

**Comment by jawj** [comment]
+1

**Comment by miry** [comment]
:+1:

**Comment by miry** [comment]
Another solution to use scopes:

``` ruby

 app.testflight.sdk = 'vendor/TestFlight'

 app.development do
    app.codesign_certificate = 'iPhone Development: Mike Jackson'
    app.provisioning_profile = <path to dev cert>
    app.entitlements['get-task-allow'] = false

    app.testflight do
      app.codesign_certificate = 'iPhone Distribution: Mike Jackson'
      app.provisioning_profile = <path to adhoc>

      app.entitlements['get-task-allow'] = false
      app.testflight.api_token  = <token>
      app.testflight.team_token = <token>
      app.testflight.app_token  = <token>
    end

  end
```

**Comment by bogardon** [comment]
+1

**Comment by chrisradford** [comment]
Closing this since TestFlight is no more and this PR is still open :)

**Pull request closed without merging**
